import type { PartCatalogEntry } from './partTypes'
import {
  DEFAULT_LOVE_LETTER_CONTENT,
  LOVE_LETTER_TEXT_LIMITS,
} from './cottageEnvelopeMetadata'

const designed = { type: 'designed' } as const

/** 花海小院室内零件独立成册，避免主目录注册表继续膨胀。 */
export const cottageInteriorPartCatalogEntries = [
  {
    id: 'cottage-single-bed',
    index: 'I—001',
    name: '温馨木床',
    englishName: 'Cozy Cottage Timber Bed',
    description: '可配置为 1.5 × 2.0 米紧凑双人床，含木床架、床垫、双枕与柔软盖毯。',
    category: '小屋家具',
    source: designed,
    kind: 'compound',
    tags: ['床', '单人床', '卧室', '木家具', '花海小院'],
    accent: '#D89A91',
    stage: '#211813',
    parameters: [
      { id: 'width', type: 'number', label: '床宽', description: '床架整体宽度。', group: '尺寸', unit: 'mm', min: 720, max: 1600, step: 10, default: 1500 },
      { id: 'length', type: 'number', label: '床长', description: '从床头到床尾的整体长度。', group: '尺寸', unit: 'mm', min: 1650, max: 2200, step: 10, default: 1900 },
      { id: 'bedHeight', type: 'number', label: '床面高度', description: '床品完成面的高度。', group: '尺寸', unit: 'mm', min: 420, max: 650, step: 10, default: 480 },
      { id: 'woodColor', type: 'color', label: '床架木色', description: '木床架综合色。', group: '外观', default: '#87542F' },
      { id: 'beddingColor', type: 'color', label: '床品颜色', description: '被褥主色。', group: '外观', default: '#F2DFD0' },
      { id: 'throwColor', type: 'color', label: '盖毯颜色', description: '床尾针织盖毯颜色。', group: '外观', default: '#C8787B' },
      { id: 'accentPillowColor', type: 'color', label: '抱枕颜色', description: '点缀抱枕颜色。', group: '外观', default: '#B86C6E' },
    ],
  },
  {
    id: 'cottage-loveseat-sofa',
    index: 'I—002',
    name: '双人沙发',
    englishName: 'Cottage Loveseat Sofa',
    description: '奶油织物双人沙发，包含软包座垫、靠背、木脚与玫瑰色抱枕。',
    category: '小屋家具',
    source: designed,
    kind: 'compound',
    tags: ['沙发', '双人沙发', '软包', '客厅', '花海小院'],
    accent: '#C97872',
    stage: '#211715',
    parameters: [
      { id: 'width', type: 'number', label: '宽度', description: '沙发扶手外沿总宽。', group: '尺寸', unit: 'mm', min: 1400, max: 2200, step: 10, default: 1720 },
      { id: 'depth', type: 'number', label: '深度', description: '沙发前后占地深度。', group: '尺寸', unit: 'mm', min: 650, max: 1000, step: 10, default: 780 },
      { id: 'height', type: 'number', label: '高度', description: '地面到靠背顶部高度。', group: '尺寸', unit: 'mm', min: 700, max: 1050, step: 10, default: 840 },
      { id: 'fabricColor', type: 'color', label: '织物颜色', description: '沙发主体布料颜色。', group: '外观', default: '#E9D8C6' },
      { id: 'pillowColor', type: 'color', label: '主抱枕', description: '主点缀抱枕颜色。', group: '外观', default: '#C87578' },
      { id: 'secondaryPillowColor', type: 'color', label: '辅抱枕', description: '第二组抱枕颜色。', group: '外观', default: '#A5A88A' },
      { id: 'woodColor', type: 'color', label: '木脚颜色', description: '沙发木脚颜色。', group: '外观', default: '#7B4A2A' },
    ],
  },
  {
    id: 'cottage-photo-frame',
    index: 'I—003',
    name: '纪念相框',
    englishName: 'Replaceable Memory Photo Frame',
    description: '支持墙挂和桌放的大小相框，内置默认纪念照片并可在室内编辑器替换图片。',
    category: '纪念展示',
    source: designed,
    kind: 'compound',
    tags: ['照片', '相框', '墙面', '桌面', '可换图'],
    accent: '#DDB16D',
    stage: '#201812',
    parameters: [
      { id: 'mount', type: 'enum', label: '安装方式', description: '选择墙挂背板或桌面支架。', group: '结构', default: 'wall', options: [{ value: 'wall', label: '墙挂' }, { value: 'table', label: '桌放' }] },
      { id: 'width', type: 'number', label: '相框宽度', description: '相框整体宽度。', group: '尺寸', unit: 'mm', min: 240, max: 900, step: 10, default: 520 },
      { id: 'height', type: 'number', label: '相框高度', description: '相框整体高度。', group: '尺寸', unit: 'mm', min: 240, max: 800, step: 10, default: 400 },
      { id: 'matWidth', type: 'number', label: '卡纸边宽', description: '照片与木框之间的卡纸宽度。', group: '结构', unit: 'mm', min: 12, max: 40, step: 2, default: 32 },
      { id: 'frameColor', type: 'color', label: '木框颜色', description: '相框木质边框颜色。', group: '外观', default: '#8A5835' },
    ],
  },
  {
    id: 'cottage-cast-iron-stove',
    index: 'I—004',
    name: '铸铁火炉',
    englishName: 'Compact Cast Iron Stove',
    description: '带玻璃炉门、把手、进气口和烟管插口的小型黑色铸铁火炉。',
    category: '小屋设施',
    source: designed,
    kind: 'compound',
    tags: ['火炉', '壁炉', '铸铁', '暖炉', '烟管'],
    accent: '#BF664E',
    stage: '#171514',
    parameters: [
      { id: 'width', type: 'number', label: '宽度', description: '火炉整体宽度。', group: '尺寸', unit: 'm', min: 0.45, max: 0.85, step: 0.01, default: 0.62 },
      { id: 'depth', type: 'number', label: '深度', description: '火炉前后深度。', group: '尺寸', unit: 'm', min: 0.38, max: 0.72, step: 0.01, default: 0.5 },
      { id: 'height', type: 'number', label: '高度', description: '不含外接烟管的整体高度。', group: '尺寸', unit: 'm', min: 0.62, max: 1.1, step: 0.01, default: 0.82 },
      { id: 'color', type: 'color', label: '铸铁颜色', description: '炉体表面颜色。', group: '外观', default: '#181716' },
      { id: 'fireLit', type: 'boolean', label: '炉火点亮', description: '显示炉膛中的暖色火焰。', group: '状态', default: true },
    ],
  },
  {
    id: 'cottage-round-table',
    index: 'I—005',
    name: '圆形木桌',
    englishName: 'Round Cottage Table',
    description: '适合信件、花束和蜡烛陈设的四人圆桌，桌面与腿架均可配置。',
    category: '小屋家具',
    source: designed,
    kind: 'compound',
    tags: ['圆桌', '木桌', '餐桌', '桌子', '花海小院'],
    accent: '#B97945',
    stage: '#21170F',
    parameters: [
      { id: 'diameter', type: 'number', label: '桌面直径', description: '圆形桌面的直径。', group: '尺寸', unit: 'm', min: 0.8, max: 1.6, step: 0.01, default: 1.15 },
      { id: 'height', type: 'number', label: '桌高', description: '地面到桌面顶部高度。', group: '尺寸', unit: 'm', min: 0.65, max: 0.86, step: 0.01, default: 0.74 },
      { id: 'topThickness', type: 'number', label: '桌面厚度', description: '圆桌面实体厚度。', group: '结构', unit: 'm', min: 0.04, max: 0.09, step: 0.005, default: 0.055 },
      { id: 'woodColor', type: 'color', label: '木材颜色', description: '桌体综合色。', group: '外观', default: '#A96E35' },
    ],
  },
  {
    id: 'cottage-wood-chair',
    index: 'I—006',
    name: '木椅',
    englishName: 'Cottage Wood Chair',
    description: '带弧形靠背和可选软垫的蜂蜜木色单椅。',
    category: '小屋家具',
    source: designed,
    kind: 'compound',
    tags: ['椅子', '木椅', '餐椅', '软垫', '花海小院'],
    accent: '#C99A62',
    stage: '#21180F',
    parameters: [
      { id: 'width', type: 'number', label: '宽度', description: '椅子整体宽度。', group: '尺寸', unit: 'm', min: 0.38, max: 0.62, step: 0.01, default: 0.46 },
      { id: 'depth', type: 'number', label: '深度', description: '椅子前后深度。', group: '尺寸', unit: 'm', min: 0.42, max: 0.7, step: 0.01, default: 0.5 },
      { id: 'height', type: 'number', label: '高度', description: '地面到靠背顶部高度。', group: '尺寸', unit: 'm', min: 0.72, max: 1.1, step: 0.01, default: 0.88 },
      { id: 'seatHeight', type: 'number', label: '坐面高度', description: '地面到坐面高度。', group: '尺寸', unit: 'm', min: 0.38, max: 0.51, step: 0.01, default: 0.46 },
      { id: 'woodColor', type: 'color', label: '木材颜色', description: '木椅综合色。', group: '外观', default: '#A96E35' },
      { id: 'cushionColor', type: 'color', label: '软垫颜色', description: '坐面软垫颜色。', group: '外观', default: '#F1E6D1' },
      { id: 'hasCushion', type: 'boolean', label: '显示软垫', description: '控制坐面软垫是否安装。', group: '结构', default: true },
    ],
  },
  {
    id: 'cottage-low-cabinet',
    index: 'I—007',
    name: '低柜与长椅',
    englishName: 'Low Cabinet / Cushioned Bench',
    description: '带柜门、抽屉和黄铜把手的长低柜，可切换为顶部软垫储物长椅。',
    category: '小屋家具',
    source: designed,
    kind: 'compound',
    tags: ['低柜', '边柜', '长椅', '储物', '抽屉'],
    accent: '#A76D42',
    stage: '#201610',
    parameters: [
      { id: 'width', type: 'number', label: '宽度', description: '柜体横向总宽。', group: '尺寸', unit: 'mm', min: 1100, max: 2600, step: 10, default: 2150 },
      { id: 'depth', type: 'number', label: '深度', description: '柜体前后深度。', group: '尺寸', unit: 'mm', min: 360, max: 620, step: 10, default: 460 },
      { id: 'height', type: 'number', label: '柜高', description: '不含长椅软垫的柜体高度。', group: '尺寸', unit: 'mm', min: 540, max: 900, step: 10, default: 760 },
      { id: 'variant', type: 'enum', label: '结构变体', description: '选择完整低柜或带软垫的储物长椅。', group: '结构', default: 'cabinet', options: [{ value: 'cabinet', label: '低柜' }, { value: 'cushioned-bench', label: '软垫长椅' }] },
      { id: 'woodColor', type: 'color', label: '木材颜色', description: '柜体综合色。', group: '外观', default: '#89542F' },
      { id: 'cushionColor', type: 'color', label: '软垫颜色', description: '长椅变体的顶部软垫颜色。', group: '外观', default: '#D8B998' },
    ],
  },
  {
    id: 'cottage-candle',
    index: 'I—008',
    name: '暖光蜡烛',
    englishName: 'Warm Cottage Candle',
    description: '可调直径、高度和蜡色的单支蜡烛，带烛芯与低成本暖色火焰。',
    category: '桌面摆件',
    source: designed,
    kind: 'compound',
    tags: ['蜡烛', '烛光', '桌面', '暖光', '摆件'],
    accent: '#F7C777',
    stage: '#211910',
    parameters: [
      { id: 'diameter', type: 'number', label: '直径', description: '蜡烛主体直径。', group: '尺寸', unit: 'm', min: 0.03, max: 0.12, step: 0.005, default: 0.065 },
      { id: 'height', type: 'number', label: '高度', description: '不含火焰的蜡烛高度。', group: '尺寸', unit: 'm', min: 0.08, max: 0.4, step: 0.01, default: 0.16 },
      { id: 'color', type: 'color', label: '蜡体颜色', description: '蜡烛主体颜色。', group: '外观', default: '#F5E4B7' },
      { id: 'lit', type: 'boolean', label: '点亮', description: '控制烛芯火焰是否显示。', group: '状态', default: true },
    ],
  },
  {
    id: 'cottage-envelope',
    index: 'I—009',
    name: '可开信封',
    englishName: 'Openable Love Letter Envelope',
    description: '写实薄纸蜡封信封，依次拆封、抽出三折信纸并接入可阅读的二维情书。',
    category: '桌面摆件',
    source: designed,
    kind: 'compound',
    tags: ['信封', '信纸', '情书', '可开合', '桌面'],
    accent: '#E9C998',
    stage: '#211A13',
    parameters: [
      { id: 'width', type: 'number', label: '宽度', description: '信封横向宽度。', group: '尺寸', unit: 'm', min: 0.14, max: 0.34, step: 0.01, default: 0.22 },
      { id: 'depth', type: 'number', label: '深度', description: '信封纵向尺寸。', group: '尺寸', unit: 'm', min: 0.1, max: 0.24, step: 0.01, default: 0.16 },
      { id: 'paperThickness', type: 'number', label: '纸张厚度', description: '信封与信纸的真实薄纸厚度。', group: '结构', unit: 'm', min: 0.0002, max: 0.001, step: 0.00005, default: 0.00035 },
      { id: 'openProgress', type: 'number', label: '打开进度', description: '0 为蜡封闭合，1 为信纸完全展开。', group: '状态', min: 0, max: 1, step: 0.01, default: 0 },
      { id: 'paperColor', type: 'color', label: '纸张颜色', description: '信封与信纸的综合色。', group: '外观', default: '#EEDDBB' },
      { id: 'sealColor', type: 'color', label: '蜡封颜色', description: '蜡封颜色。', group: '外观', default: '#B76870' },
      { id: 'letterTitle', type: 'text', label: '信件标题', description: '二维信纸顶部的标题。', group: '信件内容', maxLength: LOVE_LETTER_TEXT_LIMITS.title, default: DEFAULT_LOVE_LETTER_CONTENT.title },
      { id: 'letterSalutation', type: 'text', label: '称呼', description: '正文开始前对收信人的称呼。', group: '信件内容', maxLength: LOVE_LETTER_TEXT_LIMITS.salutation, default: DEFAULT_LOVE_LETTER_CONTENT.salutation },
      { id: 'letterBody', type: 'text', label: '正文', description: '支持换行的完整情书内容。', group: '信件内容', multiline: true, maxLength: LOVE_LETTER_TEXT_LIMITS.body, default: DEFAULT_LOVE_LETTER_CONTENT.body },
      { id: 'letterSignature', type: 'text', label: '落款', description: '信纸末尾的署名或昵称。', group: '信件内容', maxLength: LOVE_LETTER_TEXT_LIMITS.signature, default: DEFAULT_LOVE_LETTER_CONTENT.signature },
    ],
  },
  {
    id: 'cottage-string-lights',
    index: 'I—010',
    name: '柔性长线彩灯',
    englishName: 'Flexible Cottage String Lights',
    description: '由三维控制点定义路径的连续长线彩灯，按实际弧长稳定分布实例化灯泡。',
    category: '室内照明',
    source: designed,
    kind: 'compound',
    tags: ['彩灯', '串灯', '路径', '灯泡', '柔性布线'],
    accent: '#F5AD5F',
    stage: '#20170F',
    parameters: [
      { id: 'length', type: 'number', label: '预览长度', description: '零件预览中的默认展开长度；室内实例以控制点弧长为准。', group: '尺寸', unit: 'mm', min: 1000, max: 20000, step: 100, default: 6000 },
      { id: 'bulbSpacing', type: 'number', label: '灯泡间距', description: '沿路径分布灯泡的目标间距。', group: '路径', unit: 'mm', min: 120, max: 800, step: 10, default: 280 },
      { id: 'sag', type: 'number', label: '线缆下垂', description: '相邻控制点之间的最大下垂量。', group: '路径', unit: 'mm', min: 0, max: 500, step: 10, default: 110 },
      { id: 'cableColor', type: 'color', label: '线缆颜色', description: '连续电缆颜色。', group: '外观', default: '#3D3028' },
      { id: 'warmth', type: 'number', label: '暖白比例', description: '0 为琥珀色，1 为象牙暖白。', group: '光源', min: 0, max: 1, step: 0.01, default: 0.24 },
      { id: 'intensity', type: 'number', label: '发光强度', description: '灯泡自发光强度，不创建逐灯点光源。', group: '光源', min: 0, max: 6, step: 0.05, default: 1.15 },
      { id: 'lit', type: 'boolean', label: '点亮', description: '控制全部灯泡的点亮状态。', group: '光源', default: true },
    ],
  },
] as const satisfies readonly PartCatalogEntry[]
